language: node_js
notifications:
  email: raphael.aolima8@gmail.com
node_js:
- 5.12
services:
- postgresql
env:
  global:
  - NODE_ENV: test
addons:
  postgresql: "9.3"
before_install:
  - psql -c 'create database api_test; CREATE TABLE "Users" (id serial NOT NULL, name character varying(255) NOT NULL, email character varying(255) NOT NULL, password character varying(255) NOT NULL, "createdAt" timestamp with time zone NOT NULL, "updatedAt" timestamp with time zone NOT NULL, CONSTRAINT "Users_pkey" PRIMARY KEY (id));' -U postgres
  - npm install
script:
  - npm run dist-test
