language: node_js
notifications:
  email: raphael.aolima8@gmail.com
node_js:
- 5.12
services:
- postgresql
env:
  global:
  - NODE_ENV: test
  - TRAVIS: true
addons:
  postgresql: "9.3"
before_install:
  - psql -c 'create database api_test;' -U postgres
  - npm install
script:
  - npm run dist-test
