language: node_js
notifications:
  email: raphael.aolima8@gmail.com
node_js:
- 5.12
services:
- postgresql
env:
  global:
  - NODE_ENV: test
addons:
  postgresql: "9.3"
before_install:
  - sudo /etc/init.d/postgresql stop 9.3
  - sudo /etc/init.d/postgresql start 9.3
  - psql -c "ALTER USER postgres WITH PASSWORD 'pgroot'"
  - psql -c 'create database "api_test";'
  - npm i -g typescript
  - npm install
script:
- npm run dist-test
